username_field = "id:user-name"
password_field = "id:password"
login_button = "id:login-button"
error_message = "xpath://h3[@data-test='error']"
products_title = "xpath://span[@class='title']"
menu_button = "class:bm-burger-button"
logout_link = "id:logout_sidebar_link"
add_to_cart_backpack = "xpath=//div[text()='Sauce Labs Backpack']/ancestor::div[@class='inventory_item']//button"
cart_icon = "id:shopping_cart_container"
cart_title = "xpath://span[text()='Your Cart']"
remove_backpack = "xpath://button[text()='REMOVE']"
